baseurl = "/public"

# baseurl = "/public"  # set on tencent server
# baseurl = "/"  # set on netlify.com server

# relativeurls = true
title = "Smartxt Blog "
theme = "hugo-tracks-theme"
languageCode = "zh"
defaultContentLanguage = "zh"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Use custom.css for your custom styling
  style = "default"
  pages = false
  description = "Blog for Smartxt"
  copyright = "&copy;2018 Smartxt.cn"
  sidebarAbout = [
    "Blog for Smartxt.cn"  # ,
    # "Originally from Toronto, currently based in London."
  ]

  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "webmaster@txtwin.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "主站"
  url = "http://www.smartxt.cn/"

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  # facebook      = "http://www.smartxt.cn/"
  googleplus    = "http://www.smartxt.cn/"
  email         = "webmaster@txtwin.com"
  # twitter       = "full profile url in twitter"
  # linkedin      = "full profile url in linkedin"
  # stackoverflow = "full profile url in stackoverflow"
  # instagram     = "full profile url in instagram"
  github        = "https://github.com/panddas"
